### ISSUE TITLE
Missing versions?

### ISSUE THREAD

**Issue by achingbrain** [mikeal/ipjs#2]
https://www.npmjs.com/package/ipjs claims the latest version is `3.1.11`, which is tagged in this repo but the `package.json` has the version at `3.0.0`.

**Comment by mikeal** [comment]
There’s a bug, but not this one exactly.

The version should be `0.0.0-dev`. The release script pushes a new version on every merge into master so it gets incredibly noisy to do version commits on top of that. 

There are tags pushed for every release and each of those tags *does* contain a commit with the release change in package.json so if you ever need to link to a git commit hash or tag you can.

**Comment by mikeal** [comment]
fixed in https://github.com/mikeal/ipjs/commit/04a8dcbe9c1d44ec7ecdd4f6df276355eb4f3107
